name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      # run: export appVersion=$(cat ./hello-world-web-app/package.json | jq '.version')
      # echo "::set-env name=APP_NAME::$(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')"
      run: echo "::set-env name=appVersion::$(cat ./hello-world-web-app/package.json | jq '.version')"
      env:
        appVersion: 0.0.1
    - name: Publish to Registry
      run: echo "::set-env name=appVersion::$(cat ./hello-world-web-app/package.json | jq '.version')"
      env:
        appVersion: 0.0.1    
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: priyakant/hello-world-web-app-x:${{ appVersion }}
        username: priyakant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        workdir: hello-world-web-app

